### ISSUE TITLE
Practica 1 Analisis de aplicación de Realidad Aumentada

### ISSUE THREAD

**Issue by Itzelzun** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Itzelzun#2]
[Practica 1 Realidada Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Itzelzun/files/6125833/Practica.1.Realidada.Aumentada.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
